#\u914D\u7F6E\u7AEF\u53E3\u53F7
server.port=80



#\u914D\u7F6E\u6570\u636E\u6E90,\u8BA9spring\u914D\u7F6E\u6570\u636E\u5E93
spring.datasource.password=lyjLYJ123
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.username=root
#allowMultiQueries:\u6253\u5F00\u6279\u91CF\u4FDD\u5B58\uFF1BserverTimezone\uFF1A\u8BBE\u7F6E\u65F6\u95F4\u662F\u5317\u4EAC\u65F6\u95F4
spring.datasource.url=jdbc:mysql://localhost:3306/72cun?useSSL=false&allowMultiQueries=true&serverTimezone=UTC 
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource


#\u65E5\u5FD7\u8F93\u51FA\u7684\u6587\u4EF6\u5939\u8DEF\u5F84
logback.path=/72cun/log
logback.level=error

#\u6253\u5370mybatis\u7684sql
logging.level.com.lyj.dao=error


#\u6807\u8BB0\u662F\u5426\u662F\u5728\u672C\u5730\u5F00\u53D1
#environment.mark=prod


#redis
#redis.host=127.0.0.1
#redis.port=6379
#redis.timeout=3
#redis.poolMaxTotal=10
#redis.poolMaxdle=10
#redis.poolMaxWait=3
#redis.database=1

spring.redis.host=127.0.0.1
spring.redis.password=lyjLYJ123
spring.redis.port=6379
spring.redis.timeout=3000