
spring.profiles.active=dev

#\u914D\u7F6Efreemarker\u7684\u6A21\u677F\u540E\u7F00\u540D
spring.freemarker.suffix=.html

#\u914D\u7F6Exml\u7684\u6620\u5C04\u8DEF\u5F84
mybatis.mapper-locations=classpath:mapper/*.xml

#\u914D\u7F6EDruid\u6570\u636E\u6E90
spring.datasource.initialSize= 5
spring.datasource.minIdle= 5
spring.datasource.maxActive= 20
spring.datasource.maxWait= 60000
spring.datasource.timeBetweenEvictionRunsMillis= 60000
spring.datasource.minEvictableIdleTimeMillis= 300000
spring.datasource.validationQuery= SELECT 1 FROM DUAL
spring.datasource.testWhileIdle= true
spring.datasource.testOnBorrow= false
spring.datasource.testOnReturn= false
spring.datasource.poolPreparedStatements= true
#\u914D\u7F6E\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684filters\uFF0C\u53BB\u6389\u540E\u76D1\u63A7\u754C\u9762sql\u65E0\u6CD5\u7EDF\u8BA1\uFF0C'wall'\u7528\u4E8E\u9632\u706B\u5899
spring.datasource.filters= stat,wall
spring.datasource.maxPoolPreparedStatementPerConnectionSize= 20
spring.datasource.useGlobalDataSourceStat= true
spring.datasource.connectionProperties= druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

#\u914D\u7F6EjedisPool,\u7528\u4E8E\u624B\u52A8\u83B7\u53D6jedis\u8FDB\u884C\u64CD\u4F5Credis
#my-redis.host=127.0.0.1
#my-redis.port=6379
#my-redis.password=lyjLYJ123
#my-redis.timeout=3
#my-redis.database=0


