#\u652F\u4ED8\u5B9D\u652F\u4ED8\u7684\u914D\u7F6E\u6587\u4EF6

# \u652F\u4ED8\u5B9D\u7F51\u5173\u540D\u3001partnerId\u548CappId
#open_api_domain = https://openapi.alipay.com/gateway.do
open_api_domain = https://openapi.alipaydev.com/gateway.do
mcloud_api_domain = http://mcloudmonitor.com/gateway.do
pid = 2088102177581574
appid = 2016092800612198

# RSA\u79C1\u94A5\u3001\u516C\u94A5\u548C\u652F\u4ED8\u5B9D\u516C\u94A5
private_key = MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCPnqkpDbR2oG6DNO/GBY+m5prn+OZtxZOl2cIvHUwupMFlQEM7R/BYyVsmqenjtqAs9Cu6zlwd8EQVN39Opz48RJbS+kM/VUE2LfXneWAKmW2GusbGmjZhLcHilQL9S4JF/I07WQQ3AYI6379uqYLYArSoZ5ntIfdgbxVFS1G2JnAA8PpzgQomf0LaeR7kNPZq6hh14DibNaj14nfS8By5Z/uQGWBOMYgPMfMPtTTqaQOmYWw9kWYKmRFXH42fVj4NN7GN4Tggzus8guXZe4mXnq56j4rAiChO7bJB2MM2vZIOFMkL5FSbMzj8ancxJOw4KSm9kTkQwiMTPXdLzck3AgMBAAECggEAYM+RtdPALyrL8/PuIOzEvbu69d2o7pv9gBG+vOWh4ds7ZlYgO8itchwhLnng6JfFdygMhjrui1vXePnU/h7sa9HMXWFHjVyZvbzTgvolTF/KHcSvk1aGi5E9nc/WmQmaQjUQus2xcqa4s5j5wM3RHm0MfGyBrQB1cXLPwssXxJE2mir6Sn1V6OL4rXM2bHKNpWNHeHs2crTd7yeZLRxKwMJglLsw3+U6Mwz5LQ86tQ3Mvueb1jGRn6lncN/bo/8wkwWycN5h8ws6ci3MrEbzgCk1CkrQD5Fghm5LtvohScgeNrYGW5G0xlnV6cBPj/nasY6JXLlhhcMTjyeFwzvfsQKBgQDUV6UC465oAWXrTzs/OpXcw087ubTrdzZ3w1gViaDcWx5QrXlrSTOb9WX0qoBe+8mGiDX2HDcTxFAxbuCUy8roUpEVQlcSCS6joWtQFvYA0FhNkl9cQRLcnzqNvHRgNML1VsIDqL6x0OIfjvmolLbzizXvcV7TJwcV1+m2OUyHXwKBgQCtJeUKq6tXgvEa24q24tQd7/01M29qJnO5KwtyA+zEthXIuPAXQsms16RATlZlJpTE9uDlATNVpVT8PhVrdhjgiEwwwx4plYk4FbXNnziwlqnXLWoiU5IzLlGYxTe91My+7JmYdkaICPkjMD7afSb5fAdKP9l39RjDtIDTwaDFKQKBgCYeecP0BZosLhS5C4TFSqPv9+hb5SukIgYL7mMnatZEEUQgcDyfToF/40ax2Qu0HbBmAXHmDMkio9bL9csgbpOYRu1PFHxrY5ECaFZfWNg6jq+WSEIyeGVcvFE3dJjUv+71HS00/M7FFeLectkdoV5FLnCGpKQ5TF9SfGU3EhL3AoGAOExS/bY1vv2PYZkysCZuq9FFdk/kERKxm+p4DTljec5upNYlEpsfsfhnqpUOGFOEGcrf8vYB9/4K9P1Gv6sliZQnmc9HdmPtuvOsKlB0AU7rqFBW6xRbPBL6av7tEecoL4gEpQMICeFJCHz+YtJAouwF/sll71AdHj0JilCx8okCgYBq9V1Mi4SthgWz7Xq3KyDysnpxMz3Ti44ec7N/n0MFYG0W3Ov1WMioqf1wWUmPB+sXNDs0ojmZ8T+c/Jl7st2AC6mI893xtzyzsEkw1fzL3uYdriNkWpJ8Q6b6FQeAYbqQiiWDpAu98RjDyQIfzzr1THHt0OjEbntWkBUzMqMd9g==
public_key = MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAj56pKQ20dqBugzTvxgWPpuaa5/jmbcWTpdnCLx1MLqTBZUBDO0fwWMlbJqnp47agLPQrus5cHfBEFTd/Tqc+PESW0vpDP1VBNi3153lgCplthrrGxpo2YS3B4pUC/UuCRfyNO1kENwGCOt+/bqmC2AK0qGeZ7SH3YG8VRUtRtiZwAPD6c4EKJn9C2nke5DT2auoYdeA4mzWo9eJ30vAcuWf7kBlgTjGIDzHzD7U06mkDpmFsPZFmCpkRVx+Nn1Y+DTexjeE4IM7rPILl2XuJl56ueo+KwIgoTu2yQdjDNr2SDhTJC+RUmzM4/Gp3MSTsOCkpvZE5EMIjEz13S83JNwIDAQAB

#SHA256withRsa\u5BF9\u5E94\u652F\u4ED8\u5B9D\u516C\u94A5
alipay_public_key = MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1oIZeinEIUDqrV3dXI9VAElvZMJrc8MIgS+cBMjeTe1GALlnyX1caBrDDbWhFbk13S6iLsC+jrWVNblQ0kWOtKaZN7TOoV9PS3bLv78O2VzZGnpG8PeGKCC8Cc6j2yzvwfu5wHZjAgID5hAVAE8cGnUishZdJdo6ZtqWteeNeQcz+ouB9uvyeWxVU3k23khEsIdZQtNv723PIFvqUNw5nKZgWOoZRmFebeenvU2yJ5t1uQcUmcOYy0RPifMjXYpBRYZKj3r+sO+Nisl9EIWFeBPmwkycQ4LERtKSqZ7gmCqzWD6obqWil6kTrvvkeNoT+9ysO7hcW0eDaTwP8rCHBQIDAQAB

# \u7B7E\u540D\u7C7B\u578B: RSA->SHA1withRsa,RSA2->SHA256withRsa
sign_type = RSA2
# \u5F53\u9762\u4ED8\u6700\u5927\u67E5\u8BE2\u6B21\u6570\u548C\u67E5\u8BE2\u95F4\u9694\uFF08\u6BEB\u79D2\uFF09
max_query_retry = 5
query_duration = 5000

# \u5F53\u9762\u4ED8\u6700\u5927\u64A4\u9500\u6B21\u6570\u548C\u64A4\u9500\u95F4\u9694\uFF08\u6BEB\u79D2\uFF09
max_cancel_retry = 3
cancel_duration = 2000

# \u4EA4\u6613\u4FDD\u969C\u7EBF\u7A0B\u7B2C\u4E00\u6B21\u8C03\u5EA6\u5EF6\u8FDF\u548C\u8C03\u5EA6\u95F4\u9694\uFF08\u79D2\uFF09
heartbeat_delay = 5
heartbeat_duration = 900
